name: CI


on:
  
  push:
    branches: [ "main", "second" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
    Setup:
        runs-on: ubuntu-latest

        outputs:
          changed: ${{ steps.haschanged.outputs.changed }}
          
        steps:
            - name: Checkout
              uses: actions/Checkout@v3
              
            - uses: dorny/paths-filter@v2
              id: haschanged
              with:
                filters: | # TODO: Add more folders here to their appropriate program tag
                    changed: folder1/**
    build:
    
        runs-on: windows-latest

        defaults:
              run:
                shell: pwsh

        steps:
          
          - uses: actions/checkout@v3

          - name: print
            run: Get-Content branch.txt

    cond:
        needs: Setup
        runs-on: windows-latest
        if: ${{ needs.Setup.outputs.changed == 'true' }}
        steps:
          - name: print
            run: echo "changed"


       
