name: CI


on:
  
  push:
    branches: [ "main", "second" ]
  pull_request:
    branches: [ "main" ]



jobs:
    
    build:
    
        runs-on: windows-latest

        defaults:
              run:
                shell: pwsh

        steps:
          
          - uses: actions/checkout@v3

          - name: print
            shell: cmd
            run: .\fail.bat

